ips:
  redis:
    host: localhost
    port: 6379
    password: 123456
  nacos:
    ip: localhost:8848

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - name: TokenValidate
              args:
                whitePathPre:
                  - /api/user/auth

        - id: destination-service
          uri: lb://destination-service
          predicates:
            - Path=/api/destination/**
          filters:
            - name: TokenValidate
              args:
                whitePathPre:
                  - /api/destination

        - id: itinerary-service
          uri: lb://itinerary-service
          predicates:
            - Path=/api/itinerary/**
          filters:
            - name: TokenValidate
              args:
                whitePathPre:

