ips:
  mysql:
    ip: localhost
    port: 3306
    db: Itinerary-Planning-System
    username: root
    password: 123456
  nacos:
    ip: localhost
  redis:
    host: localhost
    port: 6379
    password: 123456
  sentinel:
    ip: localhost:8718