server:
  port: 8083

spring:
  profiles:
    active: local
  application:
    name: destination-service
  datasource:
    url: jdbc:mysql://${ips.mysql.ip}:${ips.mysql.port}/${ips.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${ips.mysql.username}
    password: ${ips.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000   #不能小于30秒，否则默认回到1800秒
      connection-test-query: SELECT 1
  cloud:
    nacos:
      discovery:
        server-addr: ${ips.nacos.ip} # nacos地址
    sentinel:
      transport:
        dashboard: ${ips.sentinel.ip} # sentinel dashboard地址
      http-method-specify: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  data:
    redis:
      # Redis服务器地址
      host: ${ips.redis.host}
      # Redis服务器端口号
      port: ${ips.redis.port}
      # 使用的数据库索引，默认是0
      database: 0
      # 连接超时时间
      timeout: 1800000
      # 设置密码
      password: ${ips.redis.password}

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

logging:
  level:
    com.iflove: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan:
        - com.iflove.contorller

knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-version: true
    enable-swagger-models: true